[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Cattppuccin_Mid_Dark_Borderless
Comment=An elegant GTK theme with the 'Catppuccin' colour palette based on '@Vinceliuice's Graphite' theme.
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Cattppuccin_Mid_Dark_Borderless
MetacityTheme=Cattppuccin_Mid_Dark_Borderless
IconTheme=Catppuccin_Icons
CursorTheme=Catppuccin-Mid-Dark
ButtonLayout=close,minimize,maximize:menu
