[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Cattppuccin_Macchiato_Border
Comment=An elegant GTK theme with the 'Catppuccin' colour palette, and based on '@Vinceliuice's Graphite' GTK theme.
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Cattppuccin_Macchiato_Border
MetacityTheme=Cattppuccin_Macchiato_Border
IconTheme=Cattppuccin_Macchiato
CursorTheme=Cattppuccin_Macchiato
ButtonLayout=close,minimize,maximize:menu
